"""Top-level pipeline: dark-matter quantum-sensor response analysis.

Self-consistent forward + inverse model built on the new Mathematica response
matrices:

    1. load the response matrix M and its v_min / energy grids,
    2. load the chosen halo velocity distribution eta, generated by Mathematica
       on the matrix's own v_min grid in the SAME natural units as M,
    3. forward model  observed = exposure * M @ eta  (+ background),
    4. invert: recover a monotone, non-negative flux x that reproduces the
       observed energy-bin counts (the under-determined inverse, regularised by
       the staircase/vertex selection).

Everything stays in natural units: M, the exposure and eta are all natural
units (eta comes from ``12_eta.wl``), so ``exposure * M @ eta`` is a real
expected event count -- no unit conversion or interpolation is applied.

No tuned scale factors: the exposure comes from constants, the numerical
conditioning is derived from the data, and the grids come from the data files.
"""

from __future__ import annotations

import numpy as np

from .config import RunConfig, CONDITION_C
from .data_loader import load_response_matrix, load_natural_eta
from .model import response_operator, condition
from .backgrounds import background_counts
from .optimizer import run_optimize, run_optimize_qp


class DarkMatterQuantumAnalysis:
    """Run the forward+inverse analysis for one :class:`RunConfig`."""

    def __init__(self, config: RunConfig):
        self.config = config

        # 1. response matrix + its grids (shapes/bins/v_min all come from here)
        self.rm = load_response_matrix(
            config.material, config.q, config.mass, config.nbins, run=config.run)

        # 2. natural-units velocity distribution on the matrix's v_min grid
        #    (generated by Mathematica 12_eta.wl; same units as M, no align).
        #    Three cases for the eta driving the fit:
        #      - disk_fraction = p : mixture (1-p)*Halo + p*Disk (same total DM
        #        density for any p);
        #      - eta = "Bound"     : the Earth-bound population sits ON TOP OF the
        #        full halo, so the fit eta is Bound + 100% SHM;
        #      - otherwise         : the single named model.
        #    eta_halo / eta_disk / eta_bound components are kept for the plot.
        self.eta_halo = self.eta_disk = self.eta_bound = None
        if config.disk_fraction is not None:
            p = float(config.disk_fraction)
            self.eta_halo = load_natural_eta(self.rm, "Halo")
            self.eta_disk = load_natural_eta(self.rm, "Disk")
            self.eta = (1.0 - p) * self.eta_halo + p * self.eta_disk
        elif config.eta == "Bound":
            self.eta_halo = load_natural_eta(self.rm, "Halo")
            self.eta_bound = load_natural_eta(self.rm, "Bound")
            self.eta = self.eta_halo + self.eta_bound
        else:
            self.eta = load_natural_eta(self.rm, config.eta)
            self.eta_halo = self.eta if config.eta == "Halo" else None
            self.eta_disk = self.eta if config.eta == "Disk" else None

        # 3. forward model -> observed counts
        self.m_phys = response_operator(self.rm, config.material)
        self.signal = self.m_phys @ self.eta
        self.background = background_counts(
            config.background, self.rm.ebin_low, self.rm.ebin_high)
        self.observed = self.signal + self.background

        self.result = None
        self.flux = None  # physical recovered flux x(v_min)

    # -- convenience read-only grids ----------------------------------------
    @property
    def vmin_mid(self) -> np.ndarray:
        return self.rm.vmin_mid

    @property
    def n_vmin(self) -> int:
        return self.rm.n_vmin

    @property
    def n_ebins(self) -> int:
        return self.rm.n_ebins

    # -- inversion -----------------------------------------------------------
    def optimize(self, solver: str = "osqp", x0=None, display: bool = False,
                 fix=None, vertex_select: bool = True, c=None):
        """Recover the monotone non-negative flux from the observed counts.

        Two-stage solve (kyphys-creator/neutrinoAnalysis method):

        1. minimise the Neyman chi^2 as a QP with OSQP, in the column-scaled
           variable ``x = D ⊙ y`` -- a smooth interior solution + fitted values
           ``mu = M @ x``;
        2. ``vertex_select=True`` (default) replaces that ramp with a
           piecewise-constant *vertex* reproducing the same ``mu`` via a
           tail-weighted simplex LP (the physically meaningful estimate).

        The data is never scaled, so ``self.result.fun`` is the true Neyman
        chi^2 (Delta-chi^2 intervals stay valid). Column scaling makes the
        result independent of the conditioning constant ``c``
        (``config.CONDITION_C`` when ``None``); no per-mass tuning is needed.

        The high-v tail is only weakly constrained by a handful of energy bins
        (nbins=10 helps only marginally).
        """
        if c is None:
            c = CONDITION_C

        m_cond, data_cond, bkg_cond, unscale = condition(
            self.m_phys, self.observed, self.background, c=c)

        if solver in ("osqp", "qp", "clarabel") or fix is not None:
            res = run_optimize_qp(
                m_cond, data_cond, bkg_cond, self.n_vmin,
                eps=0.0, fix=fix, vertex_select=vertex_select, verbose=display)
        else:
            res = run_optimize(
                m_cond, data_cond, bkg_cond, self.n_vmin,
                eps=0.0, x0=x0, display=display)

        self.result = res
        self.flux = unscale(res.x)        # back to physical units
        return self.flux

    # -- output (matplotlib imported lazily so it stays an optional dep) ------
    def plot(self, save: bool = True, ax=None):
        from .plotting import plot_flux_comparison
        return plot_flux_comparison(self, save=save, ax=ax)

    def save_flux(self, out_dir=None):
        from .plotting import save_flux
        return save_flux(self, out_dir=out_dir)
